version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions-all:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      go-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "bun"
    directory: "/webui"
    schedule:
      interval: "monthly"
    groups:
      js-framework-non-major:
        patterns:
          - "@sveltejs/*"
          - "svelte"
        update-types:
          - "minor"
          - "patch"
      js-tooling-non-major:
        patterns:
          - "vite"
          - "typescript"
          - "@types/*"
          - "@typescript-eslint/*"
          - "svelte-check"
          - "tailwindcss"
          - "@tailwindcss/*"
        update-types:
          - "minor"
          - "patch"
